# Generated by Django 3.2 on 2021-08-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='placeholder.jpg', null=True, upload_to='postImages')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.postimage'),
            preserve_default=False,
        ),
    ]
