# Generated by Django 3.2 on 2021-08-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210815_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(default='placeholder.jpg', upload_to='postImages'),
        ),
    ]
